[inputs]
        [inputs.csv]
                file = "testdata/hotels.csv"

[outputs]
        [outputs.json]
                file = "testdata/hotels.json"
        [outputs.xml]
                file = "testdata/hotels.xml"

[filters]
        [filters.encodingUTF8]
                enabled = true
                field = "name"
        [filters.range]
                enabled = true
                field = "stars"
                min = 0
                max = 5
        [filters.url]
                enabled = true
                field = "uri"
[aggregators]
        [aggregators.group]
        field = "name"

        [aggregators.sort]
        field = "stars"
