[inputs]
        [inputs.csv]
                # default file name is hotels.csv
                file = "data/hotels.csv"
[outputs]
        [outputs.json]
                # default file name is hotels.json
                file = "data/hotels.json"
        [outputs.xml]
                # default file name is hotels.xml
                file = "data/hotels.xml"
[filters]
        [filters.encodingUTF8]
                enabled = true
                field = "name" # field name to validate
        [filters.range]
                enabled = true
                field = "stars" # field name to validate
                min = 0         # minimum value
                max = 5         # maximal value
        [filters.url]
                enabled = true  # filter is enabled
                field = "uri"   # field name to validate
[aggregators]
        [aggregators.sorting]
                enabled = true  # aggregation is enabled
                field = "stars" # availabe fields are: stars, name, phone
